describe('Demo Practice Form', () => {
  it('Verify practice form function', () => {
    cy.visit('https://demoqa.com/automation-practice-form')
    cy.get('#firstName').type('John')
    cy.get('#lastName').type('Doe')
    cy.get('#userEmail').type('test@gmail')
    cy.get('#userNumber').type('1234567890')
    cy.get('#gender-radio-1').check()
    cy.get('#dateOfBirthInput').click()
    cy.get('.react-datepicker__month-select').select('March')
    cy.get('.react-datepicker__year-select').select('1990')
    cy.get('.react-datepicker__day--020').click()
    cy.get('#subjectsInput').type('Maths{enter}')
    cy.get('#hobbies-checkbox-1').check()
    cy.get('#currentAddress').type('123 Main St')
    cy.get('#state').click()
    cy.get('#stateCity-wrapper').contains('NCR').click()
    cy.get('#city').click()
    cy.get('#stateCity-wrapper').contains('Delhi').click()
    cy.get('#submit').click()
    cy.get('.modal-content').should('be.visible')
    cy.get('.modal-header').should('contain', 'Thanks for submitting the form')
    cy.get('.modal-body').should('contain', 'John Doe')
    cy.get('.modal-body').should('contain', 'test@gmail')
    cy.get('.modal-body').should('contain', '1234567890')
  })
})